layout_spectrum: 0.6965628
color:
  saturation: 0.2002782
  lightness: 0.779507
  brandStrength: 0.5199497
  brandColors:
    - '#006AB2'
    - '#CCF048'
    - '#282924'
    - '#51600F'
    - '#84AD29'
  rhythmicContrast: 0.9319586
typography_spectrum: 0.4548872
name: VFXi
